### ISSUE TITLE
Issue with Deploying on VPS with Public IP behind Firewall

### ISSUE THREAD

**Issue by kunger97** [haruka98/ak_oneclick_installer#11]
### This text translate by gpt, Sorry for my bad english

Server with a public IP address (let's say it's X.X.X.X).
The server, when checked using ifconfig, shows an internal IP address of 10.41.93.58.
I've successfully installed your project, **i use public ip when install.** and I can log in and reach the channel selection screen.
However, when I select CH1 and try to enter the game, it gets stuck on the "entering server" screen.
Upon checking the WorldServer logs, I noticed the following entry:
`
97514,2023/09/04 22:19:01,TCP <0x10269320:26>: connected from (null) [My Home IP]. 
97515,2023/09/04 22:19:01,[EVENT] Push CEventIdleKickout:0xf176e10
`
My question is whether the server's binary files restrict the usage of public IPs or if there's a specific configuration I need to apply to resolve this issue.

Any guidance or assistance you can provide would be greatly appreciated. Thank you for your time and your valuable open-source contribution.

**Comment by haruka98** [comment]
Sounds like your WorldServer and ZoneServer were unable to bind to the ip provided. What will not work is running the files behind a router.
First check with `ps aux | grep Server` if all servers are running.
Afterwards take a look at the `Test.log` files of the servers that crashed.

**Comment by kunger97** [comment]
I am facing another issue, which is that when I try to install WorldServer/ZoneServer on other VPS/virtual machines, it prompts a Segmentation fault.
I tried installing it on a server without a firewall (NAT) and encountered this issue when running it. Additionally, I also faced the same problem when installing it on my own computer using VMware. Does this program have specific CPU or environment requirements for execution?

**Comment by haruka98** [comment]
As the files are undocumented, I cannot give you exact details. But using `Debian 11` with `grub` and restarting after running the installer should work. As of now, Debian 12 won't work. Your server will also need to have some resources, I would recommend 4 cores and 8 GB of memory to start with.

**Comment by kunger97** [comment]
After doing some testing, I'm convinced that public servers must use the IP address show in `ifconfig`.
