### ISSUE TITLE
Link to clients on the message after the installation is done

### ISSUE THREAD

**Issue by tekinomikata** [haruka98/ak_oneclick_installer#7]
Hi, this project is a very helpful project and it would be even more awesome.

if u could add to that green message that is displayed at the end with the database password the link to download the client you choose at the start because looking thru the ragezone forums at this point is very confusing.

And since u seem to be doing it for distinct client versions that were posted, it would be really helpful if u could either add the ragezone link to the client or a mediafire/mega link to it.

best regards.

**Comment by haruka98** [comment]
Great idea! There is already such a list of links on the Discord server, but it's much better to have it on the final info screen.
Will add this asap.
